{application,elasticsearch_ex,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,any_http,jason,
                             benchee]},
              {description,"Elasticsearch_ex is a client library for Elasticsearch"},
              {modules,['Elixir.ElasticsearchEx',
                        'Elixir.ElasticsearchEx.Api.Document',
                        'Elixir.ElasticsearchEx.Api.Search',
                        'Elixir.ElasticsearchEx.Api.Utils',
                        'Elixir.ElasticsearchEx.Application',
                        'Elixir.ElasticsearchEx.Client',
                        'Elixir.ElasticsearchEx.Error',
                        'Elixir.ElasticsearchEx.Ndjson',
                        'Elixir.Inspect.ElasticsearchEx.Error']},
              {registered,[]},
              {vsn,"0.6.1"},
              {mod,{'Elixir.ElasticsearchEx.Application',[]}}]}.
